# BSV Repository Prioritizer Configuration
# Task 5: Implementation and Deliverables

# Project Settings
project:
  name: "BSV Repository Prioritizer"
  version: "1.0.0"
  description: "AI-powered GitHub repository analysis for investment sourcing"

# Data Sources
data:
  input_dataset: "data/test_task3_dataset.csv"  # Test dataset for demo
  github_token_env: "GITHUB_TOKEN"
  output_directory: "output"
  cache_directory: "data"

# Task 1: Data Collection Settings
data_collection:
  enabled: true
  rate_limit_delay: 1.0  # seconds between API calls
  max_retries: 3
  timeout: 30
  features_to_collect:
    - repository_metadata
    - activity_metrics
    - contributor_analysis
    - code_quality_indicators
    - adoption_signals
    - funding_detection

# Task 2: Feature Engineering Settings
feature_engineering:
  enabled: true
  normalize_features: true
  composite_scores:
    execution_velocity:
      - commit_velocity_score
      - release_cadence_score
      - maintenance_activity_score
      - development_consistency_score
    team_community:
      - team_resilience_score
      - community_health_score
      - growth_trajectory_score
      - network_effects_score
    technical_maturity:
      - operational_readiness_score
      - code_quality_score
      - api_stability_score
      - documentation_score
    market_positioning:
      - problem_ambition_score
      - commercial_viability_score
      - technology_differentiation_score
      - market_readiness_score

# Task 3: LLM Ranking Settings
llm_ranking:
  enabled: true
  model: "gpt-3.5-turbo"  # Cost-effective for testing
  temperature: 0.0
  max_tokens: 500
  target_comparisons: 8  # Reduced for testing
  pair_selection_strategy: "balanced"
  bradley_terry:
    max_iterations: 100
    tolerance: 1e-6

# Task 4: Final Scoring Settings
final_scoring:
  enabled: true
  weights:
    llm_preference: 0.60      # Primary signal
    technical_execution: 0.15  # Development velocity and code quality
    market_adoption: 0.15     # Community engagement and growth
    team_resilience: 0.10     # Contributor diversity and sustainability
  
  funding_gate:
    enabled: true
    min_multiplier: 0.6       # max(0.6, 1 - p_institutional_funding)
  
  normalization:
    method: "min_max"         # Normalize scores to [0,1] range
    ensure_range: [0.0, 1.0]

# Task 4: Evaluation Settings
evaluation:
  enabled: true
  ablation_studies:
    - llm_only
    - features_only
    - no_technical
    - no_market
    - equal_weights
  
  sanity_checks:
    - star_correlation
    - age_bias
    - activity_correlation
    - funding_bias
    - fork_ratio_sanity
  
  stability_analysis:
    bootstrap_iterations: 50
    confidence_level: 0.95
  
  bias_detection:
    thresholds:
      age_bias: 0.4
      popularity_bias: 0.8
      language_bias: 0.6
      size_bias: 0.5
      temporal_bias: 0.4
      funding_bias: 0.3

# Output Generation Settings
output:
  enabled: true
  formats:
    - csv
    - executive_summary
    - methodology_documentation
    - visualizations
    - pdf_report
  
  csv_columns:
    - rank
    - repo_name
    - final_score
    - llm_preference_score
    - technical_execution_score
    - market_adoption_score
    - team_resilience_score
    - funding_gate_multiplier
    - funding_risk_level
    - reason_1
    - reason_2
    - reason_3
    - investment_brief
    - methodology_version
    - analysis_date

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/bsv_analysis.log"
  console: true

# Error Handling
error_handling:
  continue_on_failure: true
  save_partial_results: true
  max_failures_per_task: 5
  retry_delays: [1, 2, 4]  # Exponential backoff

# Performance Settings
performance:
  parallel_processing: false  # Keep simple for reliability
  cache_intermediate_results: true
  memory_limit_mb: 2048
  timeout_minutes: 60

# Quality Assurance
quality_assurance:
  validate_inputs: true
  validate_outputs: true
  run_sanity_checks: true
  generate_reports: true

# Development Settings
development:
  debug_mode: false
  save_debug_files: false
  verbose_logging: false
  skip_expensive_operations: false
