data_collection:
  batch_size: 10
  enabled: true
  max_retries: 3
  rate_limit_delay: 0.5
feature_engineering:
  enabled: true
  normalize_features: true
final_scoring:
  enabled: true
  weights:
    llm_preference: 0.6
    market_adoption: 0.15
    team_resilience: 0.1
    technical_execution: 0.15
llm_ranking:
  batch_size: 5
  enabled: true
  model: gpt-3.5-turbo
  target_comparisons: 200
  temperature: 0.0
output:
  enabled: true
  formats:
  - csv
  - executive_summary
  - visualizations
project:
  name: BSV Full Dataset Analysis
  version: 1.0.0
